### PR TITLE
Refactor ABI manager & resolve deprecaton warning

### PR DESCRIPTION
**Pull request by szemate**
- Resolve deprecation warning from `ABIManager.load_abi()`
- Convert static methods of the `ABIManager` class to functions

### CODE REVIEW

**Comment by szemate** [comment]
> Can you add at least one sentence rationale for the change in the commit message?

Done

**Comment by aiman** [comment]
Thanks, it was not obvious to me what motivated the change!

**Comment by aiman** [comment]
@szemate Could you please rebase on master

**Comment by szemate** [comment]
> Could you please rebase on master

Sure, it's done

**Pull request merged**
