### PR TITLE
Add development guidelines

### PR DESCRIPTION
**Pull request by aiman**
Add development guidelines document describing the release checklist for maintainers.

### CODE REVIEW

**Review by szemate — COMMENTED** [review]
I think `RELEASE.md` and "Release Guidelines" would be more appropriate as this document is more about creating a new release than contributing to development.

**Comment by szemate** [comment]
...or the "Development" section from `README.md` could be moved into this document.

**Comment by aiman** [comment]
I've gone with latter idea of moving content out of the README, and also expanding it. @szemate could you review again and let me know your thoughts.

**Review by szemate — APPROVED** [review]

**Comment by aiman** [comment]
@szemate I've rebased on master and updated the content significantly, please take another look

**Review by szemate — APPROVED** [review]
Looks good!

**Pull request merged**
