### PR TITLE
Complete rework of the autonity library

### LINKED ISSUE #43: Drop temporary dependency on `typing-extensions`
Installing `autonity.py` was unexpectedly failing due to a `ModuleNotFoundError` that was raised by `eth-rlp`. Temporary workaround implemented in 6f9f60a was to just add `typing-extensions` as a dependency in this project. However, this would seem to be the responsibility of `eth-rlp`.

This issue is a reminder to remove the `typing-extensions` dependency from this project once the issue is resolved in `eth-rlp`.

See: https://github.com/ethereum/eth-rlp/issues/17

### PR DESCRIPTION
**Pull request by szemate**
Complete rework of the `autonity` library.
- Remove most of the old code
- Add Makefile for auto-generating contract wrappers with [pyabigen](https://github.com/clearmatics/pyabigen)
- Add the generated contract wrappers for the following contracts:
    - Accountability
    - ACU
    - Autonity
    - Inflation Controller
    - Liquid
    - Non-Stakable Vesting
    - Oracle
    - Stabilization
    - Supply Control
    - Upgrade Manager
- Add `autonity.networks` module with parameters for Piccadilly and Bakerloo testnets
- Add contract factories that retrieve contract address from the Autonity contract and check the current contract version & protocol version against the supported versions
- Add test generator for very basic sanity checks

The new library doesn't contain any of the Web3 helper functions of the old library because they mostly re-implemented existing Web3.py functionality and are out of scope of autonity.py.

All code of the `autonity.contracts` module have been auto-generated. Note that the contract ABIs are now included in the generated Python files as Python dictionaries (similarly to the [Go wrappers](https://github.com/autonity/autonity/tree/develop/params/generated)).

Closes #43 because Web3.py >=6.19.0 depends on eth-rlp 1.0.1 that includes https://github.com/ethereum/eth-rlp/pull/19 i.e. the `typing-extensions` dependency could be removed.

---

TODO:
- [x] Finalize excluded contract functions
- [x] Do not add doc comments with the `@dev` NatSpec tag to docstrings

### CODE REVIEW

**Comment by szemate** [comment]
@aiman I'm done with the contract wrapper factories as discussed, this is now ready for review.

**Comment by aiman** [comment]
I've been tracking the PR for a couple of days, there seem to be daily changes, so I'm not entirely if it's ready for final review or you need more time... Let me know @szemate

**Comment by szemate** [comment]
I've also moved a commit into https://github.com/autonity/autonity.py/pull/60

**Comment by szemate** [comment]
I've merged a number of bugfixes to `pyabigen` and re-generated the contracts in this pull request.

**Comment by szemate** [comment]
Updated the list of excluded contract functions

**Comment by aiman** [comment]
I propose exposing all the factory functions at the top-level, rather than having to import `factories`:

```
from web3 import Web3
from autonity import networks, Autonity
w3 = Web3(networks.piccadilly.http_provider)
autonity = Autonity(w3)
ntn_supply = autonity.total_supply()
```

Minor suggestion would be to use the singular `autonity.factory` (the factory module) instead of `autonity.factories` (where the factories are), because the former is shorter.

**Comment by szemate** [comment]
I've addressed the comments from https://github.com/autonity/autonity.py/pull/59#issuecomment-2373888818

**Comment by aiman** [comment]
I'm reviewing a final time, this time from the point of view of a user, and also thinking about what the Changelog entry/entries should be... Any ideas?

**Comment by szemate** [comment]
> what the Changelog entry/entries should be... Any ideas?

- Add bindings for the Accountability, ACU, Inflation Controller, Non-Stakable Vesting, Oracle, Stabilization, Supply Control and Upgrade Manager protocol contracts
- Replace bindings for the Autonity and Liquid protocol contracts, which involves breaking changes in the API
- Add constants for Autonity network parameters
- Create bindings via factory functions that fetch the actual protocol contract addresses on the given Autonity network

**Comment by aiman** [comment]
I'm having trouble running the tests for this branch inside of a devenv:

```sh
$ git checkout master
git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

$ git clean -x -d -i

$ hatch
bash: hatch: command not found

$ which python
/usr/bin/python

$ devenv shell
• Building shell ...
• Using Cachix: nixpkgs-python, devenv
warning: Performing inefficient double copy of path '«github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/' to the store. This can typically be avoided by rewriting an attribute like `src = ./.` to `src = builtins.path { path = ./.; name = "source"; }`.
✔ Building shell in 6.3s.
• Entering shell

$ which python
~/.local/share/hatch/env/virtual/autonity/H65cO8gT/autonity/bin/python

$ python --version
Python 3.11.8

$ which hatch
/nix/store/87gcqzg7cra5nrfvfilrffmv9cgp7bad-hatch-1.9.0/bin/hatch

$ hatch run +py=3.12 test:all
...
Success: no issues found in 27 source files

$ exit
exit

$ git checkout rework
Switched to branch 'rework'
Your branch is up to date with 'origin/rework'.

$ devenv shell
• Building shell ...
• Using Cachix: nixpkgs-python, devenv
warning: Performing inefficient double copy of path '«github:cachix/devenv-nixpkgs/4267e705586473d3e5c8d50299e71503f16a6fb6»/' to the store. This can typically be avoided by rewriting an attribute like `src = ./.` to `src = builtins.path { path = ./.; name = "source"; }`.
✔ Building shell in 6.1s.
• Entering shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autonity 4.0.0 requires web3==6.19.0, but you have web3 7.2.0 which is incompatible.

$ hatch run +py=3.12 test:all
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── test.py3.12 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autonity 4.0.0 requires web3==6.19.0, but you have web3 7.2.0 which is incompatible.
Traceback (most recent call last):
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/pytest/__init__.py", line 9, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/_pytest/assertion/__init__.py", line 11, in <module>
    from _pytest.assertion import rewrite
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 32, in <module>
    from _pytest.assertion import util
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/_pytest/assertion/util.py", line 24, in <module>
    from _pytest.config import Config
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/_pytest/config/__init__.py", line 58, in <module>
    import _pytest.hookspec
  File "/home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/_pytest/hookspec.py", line 305, in <module>
    @hookspec(
     ^^^^^^^^^
TypeError: HookspecMarker.__call__() got an unexpected keyword argument 'warn_on_impl_args'
```

Notice the error line:

> autonity 4.0.0 requires web3==6.19.0, but you have web3 7.2.0 which is incompatible.

This appears both on entering the devenv shell, and also when running the tests.

**Comment by szemate** [comment]
> Notice the error line:
> ```
> autonity 4.0.0 requires web3==6.19.0, but you have web3 7.2.0 which is incompatible.
> ```
> This appears both on entering the devenv shell, and also when running the tests.

This error doesn't seem to be related to devenv. I got the same without entering the devenv shell, after switching branches:
```cmd
git checkout master
hatch run true
git checkout rework
hatch run true
```
and it shows
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autonity 4.0.0 requires web3==7.2.0, but you have web3 6.19.0 which is incompatible.
```
Could it be that Hatch doesn't update the dependencies properly after switching branches?

**Comment by aiman** [comment]
It may be better to drop the devenv support for the moment, as I notice Hatch in the repo `devenv-nixpkgs/rolling` seems to be at version `1.9.0` from Dec 2023, which may be related to these issues, and in future it may be worth considering a different Python framework than Hatch since the landscape is changing quite fast.

**Comment by szemate** [comment]
> ```
> TypeError: HookspecMarker.__call__() got an unexpected keyword argument 'warn_on_impl_args'
> ```

This error appears to be a result of conflicting dependencies. As Hatch doesn't generate lockfiles, I've added the [hatch-pip-compile](https://juftin.com/hatch-pip-compile/#usage) plugin to inspect dependencies, however adding the lockfile itself resolved the error.

> It may be better to drop the devenv support for the moment, as I notice Hatch in the repo devenv-nixpkgs/rolling seems to be at version 1.9.0 

Yes this might be a Hatch bug that has been fixed, I only got the error with Hatch 1.9.0 but not with 1.12.0.

**Comment by aiman** [comment]
Can we address these test warnings?

```
tests/test_sanity.py::test_bindings_with_arbitrary_inputs[Stabilization.debt_amount]
  /home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/plum/signature.py:361: UserWarning: Could not resolve the type hint of `eth_typing.evm.ChecksumAddress`. I have ended the resolution here to not make your code break, but some types might not be working correctly. Please open an issue at https://github.com/wesselb/plum.
    annotation = resolve_type_hint(p.annotation)

tests/test_sanity.py::test_bindings_with_arbitrary_inputs[Stabilization.debt_amount]
  /home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/plum/type.py:265: UserWarning: Could not resolve the type hint of `eth_typing.evm.ChecksumAddress`. I have ended the resolution here to not make your code break, but some types might not be working correctly. Please open an issue at https://github.com/wesselb/plum.
    return _is_faithful(resolve_type_hint(x))

tests/test_sanity.py::test_bindings_with_arbitrary_inputs[Stabilization.debt_amount]
  /home/test/.local/share/hatch/env/virtual/autonity/H65cO8gT/test.py3.12/lib/python3.12/site-packages/plum/type.py:265: UserWarning: Could not determine whether `eth_typing.evm.ChecksumAddress` is faithful or not. I have concluded that the type is not faithful, so your code might run with subpar performance. Please open an issue at https://github.com/wesselb/plum.
    return _is_faithful(resolve_type_hint(x))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by szemate** [comment]
> Can we address these test warnings?

I've suppressed these warnings in ef53d77a26313adfff9476ca99af1dbe57cd7d95 and opened https://github.com/clearmatics/pyabigen/issues/7 to investigate the issue further.

These warnings are raised by the [plum](https://github.com/wesselb/plum) library that is used to handle overloaded contract functions, of which there is only one in autonity.py and it seems to be working as expected.

**Review by aiman — APPROVED** [review]
Thanks!

**Pull request merged**
